name: Bug Report
description: Report a bug
title: "[Bug]: "
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Brief description of the issue
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Explain the issue
    validations:
      required: true
